### PR TITLE
HW #7 (Microservice patterns)

### PR DESCRIPTION
**Pull request by eluyema**
- Replace transport communication between microservices from HTTP to Kafka.
- Create an Event Factory for generating the body of an event.

microservices drawio (3)

### CODE REVIEW

**Comment by cholombytko** [comment]
Good decision that you chosen Kafka. During review i did not saw any problems, so good gob with this!

**Comment by Larisa-Antsifrova** [comment]
Thank you for you work!

I might be missing it in the changes, but I do not see the timed method as per HW requirement: Метод, який виконується за розкладом, eмітить повідомлення у форматі. 

Could you please just help me out and direct me to it?)

**Comment by eluyema** [comment]
@Larisa-Antsifrova 
[subscription/src/infrastructure/notification/kafka-exchange-rate-notification.service.ts](https://github.com/GenesisEducationKyiv/software-engineering-school-4-0-eluyema/pull/8/files#diff-b1a1168a06d302784d8061641d9575752ee768cf2bac11fefbbe40484bd04efc)

I have replaced the old HTTP notification service with a new one that works with Kafka. It replaced using Nest.js DI. The notification method is triggered by TriggerSendExchangeRateNotificationApplicationImpl, and the application class method is triggered by the cron class ExchangeRateCronServiceImpl. The event, which follows the format specified in the HW requirement, is implemented in EventFactory.

**Comment by Larisa-Antsifrova** [comment]
Thank you 🌷

**Pull request merged**
